### ISSUE TITLE
Demo links not found

### ISSUE THREAD

**Issue by ByMykel** [recogito/geotagging-widget#2]
Demo links are broken. I think these are the correct ones:
- [Image annotation demo with Annotorious](https://annotorious.github.io/annotorious-v2-geotagging-widget)
- [Text annotation demo with RecogitoJS](https://annotorious.github.io/annotorious-v2-geotagging-widget/recogito-js.html)

I can open a PR if you want.

**Comment by rsimon** [comment]
Yes, that would be great thanks!
